repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v3.0.0-alpha.6'
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.40.0'
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8.39.0
          - eslint-plugin-react@6.10.3
          - eslint-config-next@13.4.1
