name: ci-deployment
run-name: Running validation for ${{ github.actor }}
on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ['ci-validation']
    types:
      - completed
jobs:
  run-build:
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn
      - run: yarn vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
